name: Release to Main

on:
  workflow_dispatch:

jobs:
  release-to-main:
    name: Push release to main
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Setup git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create release commit
        run: |
          git commit -m 'Release to main' --allow-empty

      - name: Force push the release to main
        run: |
          git push origin HEAD:main --force
