name: Update README Badges

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main

jobs:
  update-badges:
    name: Update README Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Update README badges
        run: |
          node -e "
          const fs = require('fs');
          const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          const readme = fs.readFileSync('README.md', 'utf8');
          
          // Combine both dependencies and devDependencies
          const allDeps = {
            ...packageJson.dependencies,
            ...packageJson.devDependencies
          };
          
          // Function to generate badge URL
          const getBadgeUrl = (name, version) => {
            const colors = {
              react: '61DAFB',
              typescript: '3178C6',
              vite: '646CFF',
              xstate: '121212',
              konva: '0DB7ED',
              howler: 'FF6600',
              // Add more color mappings as needed
            };
            
            const color = colors[name.toLowerCase()] || 'blue';
            return \`https://img.shields.io/badge/\${name}-\${version}-${color}?style=flat-square&logo=\${name.toLowerCase()}\`;
          };
          
          // Function to generate badge markdown
          const getBadgeMarkdown = (name, version) => {
            const badgeUrl = getBadgeUrl(name, version);
            const docsUrl = \`https://www.npmjs.com/package/\${name}\`;
            return \`[![${name}](${badgeUrl})](${docsUrl})\`;
          };
          
          // Generate badges for all dependencies
          const badges = Object.entries(allDeps)
            .filter(([name]) => {
              // List of packages we want to show badges for
              const showBadgeFor = ['react', 'typescript', 'vite', 'xstate', 'konva', 'howler'];
              return showBadgeFor.includes(name.toLowerCase());
            })
            .map(([name, version]) => {
              // Remove the ^ or ~ from version
              const cleanVersion = version.replace(/[\^~]/, '');
              return getBadgeMarkdown(name, cleanVersion);
            })
            .join('\\n');
          
          // Replace the badges section in README
          const updatedReadme = readme.replace(
            /(\[!\[.*?\].*?\n)+/,
            badges + '\\n'
          );
          
          fs.writeFileSync('README.md', updatedReadme);
          "

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: update README badges [skip ci]" && git push) 