name: Update README Badges

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main
  workflow_dispatch:

jobs:
  update-badges:
    name: Update README Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for pushing changes
      pull-requests: write # Required for pushing changes

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Update README badges
        run: node scripts/update-badge-versions.js

      - name: Create Pull Request for README badge update
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'docs: update readme badges'
          branch: update/readme-badges
          title: 'docs: update readme badges'
          body: |
            This PR updates the badges (technology shields) in the README to match the latest versions in package.json.
          base: main
          add-paths: README.md
